language: scala

cache:
  directories:
    - $HOME/.m2/repository/
    - $HOME/.ivy2/cache/
    - $HOME/.sbt/boot/
    - $HOME/.coursier

sudo: false

jdk:
  - openjdk7
  - oraclejdk8

branches:
  only:
    - develop

script:
  - ./sbt jcheckStyle
  - ./sbt test
  - ./sbt test -J-Dmsgpack.universal-buffer=true

matrix:
  include:
  - dist: trusty
    group: edge
    sudo: required
    jdk: oraclejdk9
    addons:
      apt:
        packages:
        - oracle-java9-installer
    script:
    - ./sbt test
    - ./sbt -Dmsgpack.universal-buffer=true test
